--------CREATION OF DATABASE AND SELECTION OF DATABASE AND SCHEMA-------------
CREATE OR REPLACE DATABASE BANK;
USE DATABASE BANK;
USE SCHEMA PUBLIC;


-----------------------------------------TABLE CREATION-------------------------------------------------------
CREATE OR REPLACE TABLE DISTRICT_UM(
    DISTRICT_CODE INT PRIMARY KEY,
    DISTRICT_NAME VARCHAR(100),
    REGION VARCHAR(100),
    NO_OF_INHABITANT INT,
    NO_OF_MUNCIPALITIES_WITH_INHABITANTS_LESS_499 INT,
    NO_OF_MUNCIPALITIES_WITH_INHABITANTS_500_1999 INT,
    NO_OF_MUNCIPALITIES_WITH_INHABITANTS_2000_9999 INT,
    NO_OF_MUNCIPALITIES_WITH_INHABITANTS_GREATER_10000 INT,
    NO_OF_CITIES INT,
    RATIO_OF_URBAN_INHABITANTS FLOAT,
    AVERAGE_SALARY INT,
    NO_OF_ENTERPRENURE_PER_1000_INHABITANTS INT,
    NO_OF_CRIME_COMMITTED_17 INT,
    NO_OF_CRIME_COMMITTED_18 INT
) ;


CREATE OR REPLACE TABLE ACCOUNT_UM(
    ACCOUNT_ID INT PRIMARY KEY,
    DISTRICT_ID	INT,
    frequency	VARCHAR(40),
    DATE DATE ,
    ACCOUNT_TYPE VARCHAR(100) ,
    CARD_ASSIGNED VARCHAR(20),
    FOREIGN KEY (DISTRICT_ID) references DISTRICT_UM(DISTRICT_CODE) 
);

CREATE OR REPLACE TABLE ORDER_UM (
    ORDER_ID INT PRIMARY KEY,
    ACCOUNT_ID INT,
    BANK_TO VARCHAR(45),
    ACCOUNT_TO INT,
    AMOUNT FLOAT,
    FOREIGN KEY (ACCOUNT_ID) references ACCOUNT_UM(ACCOUNT_ID)
);


CREATE OR REPLACE TABLE LOAN_UM(
    LOAN_ID NUMBER(38,0) PRIMARY KEY,
    ACCOUNT_ID NUMBER(38,0),
    DATE DATE,
    AMOUNT NUMBER(38,0),
    DURATION NUMBER(38,0),
    PAYMENTS NUMBER(38,0),
    STATUS VARCHAR(35),
    FOREIGN KEY (ACCOUNT_ID) references ACCOUNT_UM(ACCOUNT_ID)
);

CREATE OR REPLACE TABLE TRANSACTIONS_UM(
    TRANS_ID NUMBER(38,0) PRIMARY KEY,
    ACCOUNT_ID NUMBER(38,0),
    DATE DATE,
    TYPE VARCHAR(30),
    OPERATION VARCHAR(50),
    AMOUNT FLOAT,
    BALANCE FLOAT,
    PURPOSE VARCHAR(50),
    BANK VARCHAR(50),
    ACCOUNT_PARTNER_ID NUMBER(38,0),
    FOREIGN KEY (ACCOUNT_ID) references ACCOUNT_UM(ACCOUNT_ID));


CREATE OR REPLACE TABLE CLIENT_UM(
    CLIENT_ID	INT PRIMARY KEY,
    GENDER	CHAR(10),
    DOB	DATE,
    DISTRICT_ID INT,
    FOREIGN KEY (DISTRICT_ID) references DISTRICT_UM(DISTRICT_CODE) 
);


CREATE OR REPLACE TABLE DISPOSITION_UM(
    DISP_ID	INT PRIMARY KEY,
    CLIENT_ID INT,
    ACCOUNT_ID	INT,
    TYPE CHAR(15),
    FOREIGN KEY (ACCOUNT_ID) references ACCOUNT_UM(ACCOUNT_ID),
    FOREIGN KEY (CLIENT_ID) references CLIENT_UM(CLIENT_ID)
);


CREATE OR REPLACE TABLE CARD_UM(
    CARD_ID	INT PRIMARY KEY,
    DISP_ID	INT,
    TYPE CHAR(10)	,
    ISSUED DATE,
    FOREIGN KEY (DISP_ID) references DISPOSITION_UM(DISP_ID)
);


------------------------------CREATION OF FILE FORMAT-----------------------------------
CREATE OR REPLACE FILE FORMAT CSV 
    TYPE = 'csv'
    COMPRESSION = 'none'
    FIELD_DELIMITER = ','
    FIELD_OPTIONALLY_ENCLOSED_BY = 'none'
    SKIP_HEADER = 1;


--------------STORAGE INTEGRATION (AWS S3 BUCKET INTEGRATION)--------------------------

CREATE OR REPLACE STORAGE INTEGRATION S3_FINANCE_BANK_INT_UM
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = S3
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::550272757921:role/financenewrole'
    STORAGE_ALLOWED_LOCATIONS = ('s3://financesnow/');

DESC INTEGRATION S3_FINANCE_BANK_INT_UM;

---------------------------------------STAGE CREATION---------------------------------------
CREATE OR REPLACE STAGE FINANCIAL_SATGE_UM
    URL = 's3://financesnow/'
    FILE_FORMAT = CSV
    STORAGE_INTEGRATION = S3_FINANCE_BANK_INT_UM;


---------------------------------SNOW PIPE CREATION------------------------------------------
CREATE OR REPLACE PIPE ACCOUNT_PIPE_UM
    AUTO_INGEST = TRUE 
    AS
    COPY INTO "BANK"."PUBLIC"."ACCOUNT_UM" 
    FROM '@FINANCIAL_SATGE_UM/ACCOUNT/'
    FILE_FORMAT = CSV;

CREATE OR REPLACE PIPE CARD_PIPE_UM
    AUTO_INGEST = TRUE 
    AS
    COPY INTO "BANK"."PUBLIC"."CARD_UM" 
    FROM '@FINANCIAL_SATGE_UM/CARD/'
    FILE_FORMAT = CSV;

CREATE OR REPLACE PIPE CLIENT_PIPE_UM
    AUTO_INGEST = TRUE 
    AS
    COPY INTO "BANK"."PUBLIC"."CLIENT_UM" 
    FROM '@FINANCIAL_SATGE_UM/CLIENT/'
    FILE_FORMAT = CSV;

CREATE OR REPLACE PIPE DISPOSITION_PIPE_UM
    AUTO_INGEST = TRUE 
    AS
    COPY INTO "BANK"."PUBLIC"."DISPOSITION_UM" 
    FROM '@FINANCIAL_SATGE_UM/DISPOSITION/'
    FILE_FORMAT = CSV;

CREATE OR REPLACE PIPE DISTRICT_PIPE_UM
    AUTO_INGEST = TRUE 
    AS
    COPY INTO "BANK"."PUBLIC"."DISTRICT_UM" 
    FROM '@FINANCIAL_SATGE_UM/DISTRICT/'
    FILE_FORMAT = CSV;

CREATE OR REPLACE PIPE LOAN_PIPE_UM
    AUTO_INGEST = TRUE 
    AS
    COPY INTO "BANK"."PUBLIC"."LOAN_UM" 
    FROM '@FINANCIAL_SATGE_UM/LOAN/'
    FILE_FORMAT = CSV;

CREATE OR REPLACE PIPE ORDER_PIPE_UM
    AUTO_INGEST = TRUE 
    AS
    COPY INTO "BANK"."PUBLIC"."ORDER_UM" 
    FROM '@FINANCIAL_SATGE_UM/ORDER/'
    FILE_FORMAT = CSV;

CREATE OR REPLACE PIPE TRANSACTION_PIPE_UM
    AUTO_INGEST = TRUE 
    AS
    COPY INTO "BANK"."PUBLIC"."TRANSACTIONS_UM" 
    FROM '@FINANCIAL_SATGE_UM/TRNX/'
    FILE_FORMAT = CSV;


-------------------------------GET SQS NOTIFICATION CHANNEL----------------------------------
SHOW PIPES;
-------------------------------CHECK THE DATA AFTER LOAD-------------------------------------
SELECT * FROM ACCOUNT_UM;
SELECT * FROM CARD_UM;
SELECT * FROM CLIENT_UM;
SELECT * FROM DISPOSITION_UM;
SELECT * FROM DISTRICT_UM;
SELECT * FROM LOAN_UM;
SELECT * FROM ORDER_UM; 
SELECT * FROM TRANSACTIONS_UM;

ALTER PIPE TRANSACTION_PIPE_UM REFRESH;



