SELECT * FROM CLIENT_UM;
SELECT MAX(DATE), MIN(DATE) FROM TRANSACTIONS_UM;

----ADDING NEW COLUMN AGE IN THE CLIENT TABLE
ALTER TABLE CLIENT_UM
ADD AGE INT;
-----CALCULATING AGE IN
UPDATE CLIENT_UM C
SET    AGE = DATEDIFF(YEAR, C.DOB, (SELECT MAX(DATE) FROM TRANSACTIONS_UM));


-----CHECKING NULL VALUE IN THE YEAR 2016
SELECT * FROM TRANSACTIONS_UM 
WHERE BANK IS NULL AND YEAR(DATE)='2016';

-----CHECKING TOTAL TRANSACTION IN A YEAR
SELECT YEAR(DATE), COUNT(*) AS TOTAL_TRNX
FROM TRANSACTIONS_UM
GROUP BY 1
ORDER BY 1;

--------DATA TRASFORMATION FOR THE YEAR
--------RECTIFYING THE MISTAKES IN THE DATA
UPDATE TRANSACTIONS_UM
SET DATE = DATEADD(YEAR, 1, DATE)
WHERE YEAR(DATE)=2021; 

UPDATE TRANSACTIONS_UM
SET DATE = DATEADD(YEAR, 1, DATE)
WHERE YEAR(DATE)=2020;

UPDATE TRANSACTIONS_UM
SET DATE = DATEADD(YEAR, 1, DATE)
WHERE YEAR(DATE)=2019;

UPDATE TRANSACTIONS_UM
SET DATE = DATEADD(YEAR, 1, DATE)
WHERE YEAR(DATE)=2018;

UPDATE TRANSACTIONS_UM
SET DATE = DATEADD(YEAR, 1, DATE)
WHERE YEAR(DATE)=2017;

UPDATE TRANSACTIONS_UM
SET DATE = DATEADD(YEAR, 1, DATE)
WHERE YEAR(DATE)=2016;

-------AS PER REQUIREMENT WE NEED TO UPDATE THE BANK IN THE TRANSACTION TABLE FOR THE YEAR 2022
SELECT YEAR(DATE), COUNT(*) AS NULL_VALUES
FROM TRANSACTIONS_UM
WHERE BANK IS NULL
GROUP BY 1
ORDER BY 1;

UPDATE TRANSACTIONS_UM 
SET BANK = 'SKY_BANK'
WHERE BANK IS NULL AND YEAR(DATE)=2022;


----------AS PER THE REQUIREMENT IN YEAR 2021 DBS BANK IS LAUNCHED AND DATA IS MISSING UPDATE IT
UPDATE TRANSACTIONS_UM
SET BANK = 'DBS BANK'
WHERE BANK IS NULL AND YEAR(DATE)=2021;

----------FOR YEAR 2019 UPDATE NULL WITH NORTHEN BANK
UPDATE TRANSACTIONS_UM 
SET BANK = 'NORTHEN BANK'
WHERE BANK IS NULL AND YEAR(DATE)=2019;

-----FOR YEAR 2018 UPDATE NULL WITH SOUTHERN BANK
UPDATE TRANSACTIONS_UM 
SET BANK = 'SOUTHERN BANK'
WHERE BANK IS NULL AND YEAR(DATE)=2018;

-----FOR YEAR 2017 UPDATE NULL WITH ADB
UPDATE TRANSACTIONS_UM 
SET BANK = 'ADB BANK'
WHERE BANK IS NULL AND YEAR(DATE)=2017;

------------------CHECK FOR NULL 
SELECT YEAR(DATE), COUNT(*) AS NULL_VALUES
FROM TRANSACTIONS_UM
WHERE BANK IS NULL
GROUP BY 1
ORDER BY 1;



---------------CARD TABLE 
SELECT * FROM CARD_UM;
---------------CHECK YEAR 
SELECT DISTINCT YEAR(ISSUED) FROM CARD_UM;

-----UPDATE YEAR FROM 2016 TO 2021 BY 1 YEAR
UPDATE CARD_UM
SET ISSUED = DATEADD(YEAR, 1, ISSUED)
WHERE YEAR(ISSUED)=2021;

UPDATE CARD_UM
SET ISSUED = DATEADD(YEAR, 1, ISSUED)
WHERE YEAR(ISSUED)=2020;

UPDATE CARD_UM
SET ISSUED = DATEADD(YEAR, 1, ISSUED)
WHERE YEAR(ISSUED)=2019;

UPDATE CARD_UM
SET ISSUED = DATEADD(YEAR, 1, ISSUED)
WHERE YEAR(ISSUED)=2018;

UPDATE CARD_UM
SET ISSUED = DATEADD(YEAR, 1, ISSUED)
WHERE YEAR(ISSUED)=2017;

UPDATE CARD_UM
SET ISSUED = DATEADD(YEAR, 1, ISSUED)
WHERE YEAR(ISSUED)=2016;


----ACCOUNT
SELECT DISTINCT YEAR(DATE) , COUNT(*) AS TOT_ACC
FROM ACCOUNT_UM
GROUP BY 1
ORDER BY 1;
